import { Peer } from "./module/peer.js";
import { PeerConnectionUI } from "./ui-interaction.js";

/** Is a handshake from this host currently being processed by the remote */
const _runState = new WeakMap(),
    _ui = new WeakMap();

/** A Peer Connection Manager designed to negotiate the connection via manually sending handshakes */
class UINegotiatedPeer extends Peer {
    constructor() {
        // Instantiate with the default data channel named "message"
        super({ defaultDataChannel: `message` });

        // Add the UI for this connection
        _ui.set(
            this,
            new PeerConnectionUI({
                StartConnection: () => this.StartConnectionProcess(),
                ConsumeRemoteHandshake: params => this.ConsumeRemoteHandshake(params),
                SendChatMessage: text => this.dataChannel.Send(text, `message`),
                SendTypingStatus: status => this.dataChannel.Send(status, `typing-status`),
            })
        );

        // Add a second data channel called "typing-status"
        this.dataChannel.AddOutboundChannel(`typing-status`);

        // Track the handshake negotiation on the remote side
        _runState.set(this, { currentlyProcessingHandshake: false });

        // Handle newly created handshake values
        this.onGeneratedHandshake = () => {
            this.ui.ShowNextHandshake({
                runState: _runState.get(this),
                generatedHandshakes: this.generatedHandshakes,
            });
        };

        // Respond to Inbound messages
        this.dataChannel.onInboundMessage = (channel, evt) => this.ui.RemoteMessageHandler(channel, evt);

        // When the outbound channel is opened for this connection
        this.dataChannel.outbound.get(`message`).onOpen = (evt) => {
            const channel = evt.target;

            if (channel.readyState == `open`) {
                // Clear any unused handshake values
                this.generatedHandshakes.splice(0, this.generatedHandshakes.length);

                // Display the chat UI
                this.ui.ActivateMessaging();
            }
        };
    }

    get ui() { return _ui.get(this); }

    /*
     * --------------------------------------------------------------
     * Public Methods
     * --------------------------------------------------------------
     */

    /** Handle negotiation values generated by the remote host */
    async ConsumeRemoteHandshake({ rawHandshake }) {
        if (rawHandshake.length > 0) {
            _runState.get(this).currentlyProcessingHandshake = false;

            try {
                await this.ConsumeHandshake(rawHandshake);

                this.ui.ShowNextHandshake({
                    runState: _runState.get(this),
                    generatedHandshakes: this.generatedHandshakes,
                });
            } catch (err) {
                if (err.name == `SAME ORIGIN HANDSHAKE`)
                    alert(err.message);
                else
                    throw err;
            }
        }
    }

    /** Start the negotiation process for a new connection */
    async StartConnectionProcess() {
        _runState.get(this).currentlyProcessingHandshake = false;
        await this.InitiateConnection();
    }

    /* -------------------------------------------------------------- */
}

export {
    UINegotiatedPeer,
};
